name: Generate Test Report

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  test:
    name: Generate Test Report
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev

      - name: Install allure commandline
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure_2.29.0-1_all.deb
          sudo dpkg -i allure_2.29.0-1_all.deb

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FastAPI server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &

      - name: Wait for FastAPI server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=./allure-results tests/test_main.py -v

      - name: Check Allure results
        run: ls -l ./allure-results

      - name: Generate Allure report
        run: |
          allure generate ./allure-results --clean -o ./allure-report || (echo "Allure report generation failed"; exit 1)

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Cleanup
        run: |
          kill $(lsof -t -i:8000)
          rm -rf ./allure-results ./allure-report
