name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"

env:
  DOCKER_IMAGE_NAME: my-docker-image
  DOCKER_CONTAINER_NAME: my-docker-container

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      - name: Save docker image
        run: docker save ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -o ${{ env.DOCKER_IMAGE_NAME }}.tar
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOCKER_IMAGE_NAME }}
          path: ${{ env.DOCKER_IMAGE_NAME }}.tar

  run:
    name: Run Container
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DOCKER_IMAGE_NAME }}
      - name: Load docker image
        run: docker load -i ${{ env.DOCKER_IMAGE_NAME }}.tar
      - name: Run docker image
        run: docker run -dit --name ${{ env.DOCKER_CONTAINER_NAME }} -p 8000:8000 ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash

  test:
    needs: run
    name: Test Container Image with Pytest
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.DOCKER_IMAGE_NAME }}
      - name: Load docker image
        run: docker load -i ${{ env.DOCKER_IMAGE_NAME }}.tar
      - name: Run docker image
        run: docker run -dit --name ${{ env.DOCKER_CONTAINER_NAME }} -p 8000:8000 ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash
      - name: HTTP request to server
        run: docker exec ${{ env.DOCKER_CONTAINER_NAME }} pytest tests/test_main.py
