name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build . --file Dockerfile --tag my-docker-image:${{ github.sha }}
      - name: Save docker image
        run: docker save my-docker-image:${{ github.sha }} -o my-docker-image.tar
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-docker-image
          path: my-docker-image.tar

  run:
    name: Run Container
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: my-docker-image
      - name: Load docker image
        run: docker load -i my-docker-image.tar
      - name: Run docker image
        run: docker run -dit --name my_docker_container -p 8000:8000 my-docker-image:${{ github.sha }}
      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash

  test:
    needs: run
    name: Test Container Image with Pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build . --file Dockerfile --tag my-docker-image:${{ github.sha }}

      - name: Run docker image
        run: docker run -dit --name my_docker_container -p 8000:8000 my-docker-image:${{ github.sha }}

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash

      - name: HTTP request to server
        run: docker exec my_docker_container pytest tests/test_main.py
