name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-docker-image:${{ github.sha }}

  run:
    name: Run Container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-docker-image:${{ github.sha }}

      - name: Run the Docker image
        run: docker run -dit --name my_docker_container -p 8000:8000 my-docker-image:${{ github.sha }}

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash

  test:
    needs: run
    name: Test the WebAPI with Container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-docker-image:${{ github.sha }}

      - name: Run the Docker image
        run: docker run -dit --name my_docker_container -p 8000:8000 my-docker-image:${{ github.sha }}

      - name: Wait for server to be ready
        run: |
          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
        shell: bash

      - name: HTTP Request to the FastAPI server
        run: docker exec my_docker_container pytest tests/test_main.py

